sudo: false
language: go
go:
  - 1.9.x
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
matrix:
  allow_failures:
    - go: master
  fast_finish: true
notifications:
  email: false
